# name: deploy
# on: workflow_dispatch

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Docker
#         uses: docker/setup-buildx-action@v2

#       - name: Build and run Docker
#         run: |
#           docker build -t ml-api .
#           docker run -d -p 5000:5000 ml-api
##########################################################
name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and run Docker
        run: |
          docker build -t ml-api .
          docker run -d -p 5000:5000 ml-api
